#pragma config(Sensor, in2,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, dgtl10, LeftButan,      sensorTouch)
#pragma config(Sensor, dgtl11, RightButan,     sensorTouch)
#pragma config(Motor,  port2,           TopWheel,      tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           ElctroDeMagnet, tmotorVex393, openLoop)
#pragma config(Motor,  port10,          armMotor,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int threshold = 505;
	while(1 == 1)
  {
  	if(vexRT[Btn6U] == 1)
    {
    	bool t = true;
    	int b = 0;
    	while(t == true){
    		while(b < 10000){
	    		// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+
			    displayLCDCenteredString(0, "LEFT  CNTR  RGHT");        //  Display   |
			    displayLCDPos(1,0);                                     //  Sensor    |
			    displayNextLCDNumber(SensorValue(lineFollowerLEFT));    //  Readings  |
			    displayLCDPos(1,6);                                     //  to LCD.   |
			    displayNextLCDNumber(SensorValue(lineFollowerCENTER));  //            |
			    displayLCDPos(1,12);                                    //  L  C  R   |
			    displayNextLCDNumber(SensorValue(lineFollowerRIGHT));   //  x  x  x   |
			    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+

			    // RIGHT sensor sees dark:
			    if(SensorValue(lineFollowerRIGHT) > threshold)
			    {
			      // counter-steer right:
			      motor[leftMotor]  = -25;
			      motor[rightMotor] = 25;
			    }
			    // CENTER sensor sees dark:
			    else if(SensorValue(lineFollowerCENTER) > threshold)
			    {
			      // go straight
			      motor[leftMotor]  = 30;
			      motor[rightMotor] = 30;
			    }
			    // LEFT sensor sees dark:
			    else if(SensorValue(lineFollowerLEFT) > threshold)
			    {
			      // counter-steer left:
			      motor[leftMotor]  = 25;
			      motor[rightMotor] = -25;
			    }
			    if(vexRT[Btn6D] == 1){
			    	t = false;
			    	b = 10000;
			    }
		  	}
		  	while(SensorValue[RightButan] == 0){
		  		motor[ElctroDeMagnet] = 127;
		  		motor[TopWheel] = 40;
		  		if(vexRT[Btn6D] == 1){
			    	t = false;
			    	break;
			    }
		  	}
		  	while(SensorValue[LeftButan] == 0){
		  		motor[ElctroDeMagnet] = 0;
		  		motor[TopWheel] = -40;
		  		if(vexRT[Btn6D] == 1){
			    	t = false;
			    	break;
			    }
		  	}


    	}
    }

    if(vexRT[Btn8D] == 1)
    {
    	motor[ElctroDeMagnet] = 127;
    }
    if(vexRT[Btn8U] == 1)
    {
    	motor[ElctroDeMagnet] = 0;
    }

	//Driving Motor Control
    motor[leftMotor] = vexRT[Ch3] / 2;
    motor[rightMotor] = vexRT[Ch2] / 2;
    //Arm Control
    if(vexRT[Btn8R] == 1)
    {
    	if(SensorValue[RightButan] == 1)
    	{
    		motor[TopWheel] = -40;
    		wait1Msec (10);
    	}
   		else
   		{
      motor[TopWheel] = 40;
    	}
    }
    else if(vexRT[Btn8L] == 1)
    {
    	if(SensorValue[LeftButan] == 1)
    	{
    		motor[TopWheel] = 40;
    		wait1Msec (10);
    	}
   		else
   		{
      motor[TopWheel] = -40;
    	}
    }
    else
    {
      motor[TopWheel] = 0;
    }
  }
}
